### ISSUE TITLE
Styling is broken on the email input on /account

### ISSUE THREAD

**Issue by kingjacob** [unioncredit/union-v1-interface#20]
**What it looks like:**
<img width="795" alt="Screen Shot 2020-04-25 at 3 34 18 AM" src="https://user-images.githubusercontent.com/806312/80275306-0b453700-86a6-11ea-89ea-968b06a7df3d.png">

**What it should look like:**
<img width="575" alt="Screen Shot 2020-04-25 at 3 36 34 AM" src="https://user-images.githubusercontent.com/806312/80275308-0d0efa80-86a6-11ea-9a42-0e0cec101ac0.png">

**Comment by mirshko** [comment]
fixed in ebc55e2c0769f42a7cd5f11f57fa8f70957e49cb
