### ISSUE TITLE
Implement Payment Due Logic

### ISSUE THREAD

**Issue by mirshko** [unioncredit/union-v1-interface#8]
BorrowModal

Seems Payment Due isn't added yet? 

If someone is going to make a new borrow it should be `Today + 30 Days`

Unless this will be set manually?

<img width="467" alt="Screen Shot 2020-04-23 at 14 27 54" src="https://user-images.githubusercontent.com/8116716/80099385-a63af580-856e-11ea-8ec5-d59208cdb4b8.png">

<img width="416" alt="Screen Shot 2020-04-23 at 14 25 16" src="https://user-images.githubusercontent.com/8116716/80099135-47757c00-856e-11ea-886b-77fef0238fca.png">

**Comment by kingjacob** [comment]
The logic is if the person has an outstanding balance to use the existing
payment due date, same method as used tocalculated in the repay component
on the /borrow page. But if this is a fresh borrow, then the payment due
date will be now + {payment period, which is set to ~30 days in blocktime}
